# Welcome to Jekyll!
title: Eric Eastman
url: https://eastmaner.com
baseurl:

# Sass setting
sass:
  sass_dir: _sass
  style:    compressed

# Custom
lang: en                    # html lang
open: true                  # open or close your site
date_format: "%Y-%m-%d"     # date format
theme_color: "#1DA1F2"      # your favorite theme color
allow_search_engines: true  # allow search engines indexing your resume
analytics:
  google: G-T3FS6NPCW7
# cloudflare:
